export const ProfileData = [
    {
        name: "Rajput B",
        profile_id: "AXO2637",
        title: "PHP Developer",
        years: "4",
        skills: ["HTML", "HTML 5", "PHP", "JavaScript", "API", "MySQL", "React JS", "JQuery", "MongoDB"],
        summary: "● I Have 4+ years of experience in Core php, Codeigniter and Laravel development. ● Establishing and guiding the website’s architecture ● Ensuring high-performance and availability, and managing all technical aspects of the CMS ● Helping formulate an effective, responsive design and turning it into a working theme and custom scripts. ● Good knowledge and experience in MySql, AJAX, XML,Java Script etc. ● Excellent code reviews and code debugging skills. ● Strong experience in writing MySql queries. ● Understanding of MVC (Model View Controller) software architectural pattern. ● Documenting bug reports and any code changes. ● Possess good verbal and written communication skills",
        industries: ["Entertainment", "Insurance"],

        projects: [
            {
                title: "Rajhans",
                description: "A movie ticket booking portal where users can browse, select, and purchase tickets for movies playing in theaters",
                roles: "● Build seat chart dashboards for real-time data visualization, Seats Management ● Build Dashboard for movie management. ● Optimized data fetching algorithms. ● Developed Mobile APIs ● Intuitive Admin Panel ● Set Booking Options ● Active Selections on Graphic Map ● Sector Tickets ● PDF Ticket Generation",
                tech: "PHP Codeigniter 4, Javascript, jQuery, MySQL (Back End)",
                industry: "Entertainment",
            },
            {
                title: "OLocker",
                description: "This is a Jewelry Management system. A unique concept of providing Insurance on Jewelry",
                roles: "● Build an interactive system for managing jewellery● Network management system for users ● Optimized queries operating from more than 100 tables ● Developed and implement Mobile APIs ● Integrated 3rd party APIs ● Insurance module for all 3 user level ● EMI module (Integrated 2+ 3rd party partners APIs) ● Product management ● Customer management ● Offer management ● Push notification panel",
                tech: "Codeigniter 4, MySql, jQuery, Javascript",
                industry: "Insurance",
            }
        ]
    },
    {
        name: "DA R",
        profile_id: "AXO2408 ",
        title: "Sr Python Developer",
        years: "7",
        skills: ["Python", "Flask", "Django"],
        summary: "Over 7+ years of experience in Design and Development, and implementation of various client-server enterprise applications in Python using web frameworks like Django, Flask, Django REST framework, GraphQL, Microservices, Selenium.",
        industries: ["Ecommerce", "Food Delivery"],
    },
    {
        name: "Lingayat J",
        profile_id: "AXO2341",
        title: "PHP developer",
        years: "2",
        skills: ["Operating System", "Scripting Languages", "Windows"],
        summary: "I'm a versatile pro in web development and database management, blending commerce education with IT skills. My roles span logistics, advertising strategy, and PHP development, with expertise in PHP, MySQL, CodeIgniter, and web tech. I'm all about optimization and effective communication, a valuable asset to any team.",
        industries: ["Ecommerce", "Healthcare", "Information Technology"],
    },
    {
        name: "del Cid D",
        profile_id: "AXO2579",
        title: "Senior Software Developer / Architect",
        years: "10",
        skills: ["JavaScript", ".Net Core", ".NET Framework"],
        summary: "Experienced Senior Software Engineer with a strong background in leadership and team management. Proficient in a wide range of technologies, including Net Core, Node.js, React, TypeScript, Angular, SQL, NoSQL, Docker, AWS, Azure, Microservices, SOLID, and Design patterns. ",
        industries: ["Software development"],
    },
    {
        name: "Castillo J ",
        profile_id: "AXO2420 ",
        title: "Tech-Lead & Senior Software Developer",
        years: "13",
        skills: ["C#", "SQL Server", "Bootstrap"],
        summary: "Software Engineer with 12+ years of experience as a Full stack Developer, experience developing commercial software. Attentive to quality of work in every stage of the development lifecycle from design, coding, debugging, testing, and maintenance. Advanced skills and knowledge of programming tools and development practices.",
        industries: ["Artificial Intelligence", "Nearshore", "Ecommerce"],
    },
    {
        name: "Smith S",
        profile_id: "AXO2483  ",
        title: "Business Analyst",
        years: "6",
        skills: ["Java", "Spring Boot", "Hybernate"],
        summary: "6 Years of experience as a Software Developer with expertise in delivering end-to-end IT projects. Strong domain knowledge in Loan Originating System (LOS) and Loan Management System (LMS). Committed to fostering partnerships with customers and stakeholders.",
        industries: ["Financial Services", "Supply Chain Finance"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
    {
        name: "PR L",
        profile_id: "AXO2375",
        title: "Salesforce Developer",
        years: "3",
        skills: ["Salesforce CPQ", "Salesforce Lightning", "Salesforce Development"],
        summary: "A passionate Salesforce Developer with experience in developing, implementing, and customizing Salesforce Enterprise applications across the full development cycle from requirement analysis and development to testing and deployment. Experience includes Apex and Visualforce, CPQ, LWC, Salesforce Lightning Component, Trigger, Workflow, and Salesforce Lightning Components.",
        industries: ["Ecommerce", "SaaS"],
    },
];
